image:
  registry: docker.io
  repository: bitnami/postgresql
  tag: "16.3.0"
  pullPolicy: IfNotPresent
auth:
  enablePostgresUser: true
  database: "superset" # Create a new database used by Superset later on
  username: "superset" # Create a new user used by Superset later on
  password: "super-secret-password-superset-admin" # Change password used by "superset" user
  postgresPassword: "super-secret-password-postgres" # Change password used by "postgres" user
architecture: standalone
containerPorts:
  postgresql: 5432
postgresqlDataDir: /bitnami/postgresql/data
primary:
  name: primary
  resourcesPreset: "large"
  service:
    type: ClusterIP
    ports:
      postgresql: 5432
  persistence:
    enabled: true
  persistentVolumeClaimRetentionPolicy:
    enabled: true
    whenScaled: Retain
    whenDeleted: Retain